name: DataStamp
options:
  bundleIdPrefix: com.makiavel
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "6.0"
    SWIFT_STRICT_CONCURRENCY: complete
    ENABLE_USER_SCRIPT_SANDBOXING: true
    DEVELOPMENT_TEAM: 84P86W64VJ
    CODE_SIGN_STYLE: Automatic

targets:
  DataStamp:
    type: application
    platform: iOS
    sources:
      - path: DataStamp
        excludes:
          - "**/.DS_Store"
      - path: DataStamp/Resources/Assets.xcassets
      - path: DataStamp/Resources/en.lproj
      - path: DataStamp/Resources/pt-BR.lproj
    settings:
      base:
        INFOPLIST_FILE: DataStamp/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.makiavel.datestamp
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: false
    entitlements:
      path: DataStamp/DataStamp.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.makiavel.datestamp
        # iCloud disabled temporarily - configure in Apple Developer Portal first
        # com.apple.developer.icloud-services:
        #   - CloudKit
        # com.apple.developer.icloud-container-identifiers:
        #   - iCloud.com.makiavel.datestamp
    dependencies:
      - target: DataStampShareExtension
        embed: true
      - target: DataStampWidget
        embed: true
    info:
      path: DataStamp/Info.plist
      properties:
        CFBundleName: DataStamp
        CFBundleDisplayName: DataStamp
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundlePackageType: APPL
        CFBundleExecutable: $(EXECUTABLE_NAME)
        UILaunchScreen:
          UIColorName: ""
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        NSCameraUsageDescription: "DataStamp needs camera access to timestamp photos"
        NSPhotoLibraryUsageDescription: "DataStamp needs photo library access to timestamp existing photos"

  DataStampShareExtension:
    type: app-extension
    platform: iOS
    sources:
      - path: DataStampShareExtension
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.makiavel.datestamp.share
        INFOPLIST_FILE: DataStampShareExtension/Info.plist
        SKIP_INSTALL: true
        CODE_SIGN_ENTITLEMENTS: DataStampShareExtension/DataStampShareExtension.entitlements
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
    entitlements:
      path: DataStampShareExtension/DataStampShareExtension.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.makiavel.datestamp
    info:
      path: DataStampShareExtension/Info.plist
      properties:
        CFBundleName: Share to DataStamp
        CFBundleDisplayName: DataStamp
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundlePackageType: XPC!
        CFBundleExecutable: $(EXECUTABLE_NAME)
        NSExtension:
          NSExtensionPointIdentifier: com.apple.share-services
          NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).ShareViewController
          NSExtensionAttributes:
            NSExtensionActivationRule:
              NSExtensionActivationSupportsFileWithMaxCount: 1
              NSExtensionActivationSupportsImageWithMaxCount: 1
              NSExtensionActivationSupportsText: true
              NSExtensionActivationSupportsWebURLWithMaxCount: 1

  DataStampWidget:
    type: app-extension
    platform: iOS
    sources:
      - path: DataStampWidget
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.makiavel.datestamp.widget
        INFOPLIST_FILE: DataStampWidget/Info.plist
        SKIP_INSTALL: true
        CODE_SIGN_ENTITLEMENTS: DataStampWidget/DataStampWidget.entitlements
        ASSETCATALOG_COMPILER_WIDGET_BACKGROUND_COLOR_NAME: WidgetBackground
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
    entitlements:
      path: DataStampWidget/DataStampWidget.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.makiavel.datestamp
    info:
      path: DataStampWidget/Info.plist
      properties:
        CFBundleName: DataStamp Widget
        CFBundleDisplayName: DataStamp
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundlePackageType: XPC!
        CFBundleExecutable: $(EXECUTABLE_NAME)
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension

  DataStampTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: DataStampTests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.makiavel.datestamp.tests
        TEST_HOST: $(BUILT_PRODUCTS_DIR)/DataStamp.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/DataStamp
        BUNDLE_LOADER: $(TEST_HOST)
        GENERATE_INFOPLIST_FILE: true
    dependencies:
      - target: DataStamp
