name: Witness
options:
  bundleIdPrefix: com.makiavel
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "6.0"
    SWIFT_STRICT_CONCURRENCY: complete
    ENABLE_USER_SCRIPT_SANDBOXING: true
    DEVELOPMENT_TEAM: 84P86W64VJ
    CODE_SIGN_STYLE: Automatic

targets:
  Witness:
    type: application
    platform: iOS
    sources:
      - path: Witness
        excludes:
          - "**/.DS_Store"
          - "**/*.xcassets"
    resources:
      - path: Witness/Resources/Assets.xcassets
    settings:
      base:
        INFOPLIST_FILE: Witness/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.makiavel.witness
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: false
    entitlements:
      path: Witness/Witness.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.makiavel.witness
    dependencies:
      - target: WitnessShareExtension
        embed: true
      - target: WitnessWidget
        embed: true
    info:
      path: Witness/Info.plist
      properties:
        CFBundleName: Witness
        CFBundleDisplayName: Witness
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundlePackageType: APPL
        CFBundleExecutable: $(EXECUTABLE_NAME)
        UILaunchScreen:
          UIColorName: ""
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        NSCameraUsageDescription: "Witness needs camera access to timestamp photos"
        NSPhotoLibraryUsageDescription: "Witness needs photo library access to timestamp existing photos"

  WitnessShareExtension:
    type: app-extension
    platform: iOS
    sources:
      - path: WitnessShareExtension
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.makiavel.witness.share
        INFOPLIST_FILE: WitnessShareExtension/Info.plist
        SKIP_INSTALL: true
        CODE_SIGN_ENTITLEMENTS: WitnessShareExtension/WitnessShareExtension.entitlements
    entitlements:
      path: WitnessShareExtension/WitnessShareExtension.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.makiavel.witness
    info:
      path: WitnessShareExtension/Info.plist
      properties:
        CFBundleName: Share to Witness
        CFBundleDisplayName: Witness
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundlePackageType: XPC!
        CFBundleExecutable: $(EXECUTABLE_NAME)
        NSExtension:
          NSExtensionPointIdentifier: com.apple.share-services
          NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).ShareViewController
          NSExtensionAttributes:
            NSExtensionActivationRule:
              NSExtensionActivationSupportsFileWithMaxCount: 1
              NSExtensionActivationSupportsImageWithMaxCount: 1
              NSExtensionActivationSupportsText: true
              NSExtensionActivationSupportsWebURLWithMaxCount: 1

  WitnessWidget:
    type: app-extension
    platform: iOS
    sources:
      - path: WitnessWidget
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.makiavel.witness.widget
        INFOPLIST_FILE: WitnessWidget/Info.plist
        SKIP_INSTALL: true
        CODE_SIGN_ENTITLEMENTS: WitnessWidget/WitnessWidget.entitlements
        ASSETCATALOG_COMPILER_WIDGET_BACKGROUND_COLOR_NAME: WidgetBackground
    entitlements:
      path: WitnessWidget/WitnessWidget.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.makiavel.witness
    info:
      path: WitnessWidget/Info.plist
      properties:
        CFBundleName: Witness Widget
        CFBundleDisplayName: Witness
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundlePackageType: XPC!
        CFBundleExecutable: $(EXECUTABLE_NAME)
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
