name: Witness
options:
  bundleIdPrefix: com.makiavel
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "6.0"
    SWIFT_STRICT_CONCURRENCY: complete
    ENABLE_USER_SCRIPT_SANDBOXING: true
    DEVELOPMENT_TEAM: 84P86W64VJ
    CODE_SIGN_STYLE: Automatic

targets:
  Witness:
    type: application
    platform: iOS
    sources:
      - path: Witness
        excludes:
          - "**/.DS_Store"
          - "**/*.xcassets"
    resources:
      - path: Witness/Resources/Assets.xcassets
    settings:
      base:
        INFOPLIST_FILE: Witness/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.makiavel.witness
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: false
    info:
      path: Witness/Info.plist
      properties:
        CFBundleName: Witness
        CFBundleDisplayName: Witness
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundlePackageType: APPL
        CFBundleExecutable: $(EXECUTABLE_NAME)
        UILaunchScreen:
          UIColorName: ""
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        NSCameraUsageDescription: "Witness needs camera access to timestamp photos"
        NSPhotoLibraryUsageDescription: "Witness needs photo library access to timestamp existing photos"
